ALTER TYPE "SessionType" ADD VALUE IF NOT EXISTS 'MEAT_DISTRIBUTION';
ALTER TYPE "SessionType" ADD VALUE IF NOT EXISTS 'LOGISTICS_COMPLETENESS';

ALTER TABLE "work_schedules"
ADD COLUMN IF NOT EXISTS "meatDistributionStart" TEXT NOT NULL DEFAULT '13:00',
ADD COLUMN IF NOT EXISTS "meatDistributionEnd" TEXT NOT NULL DEFAULT '16:00',
ADD COLUMN IF NOT EXISTS "logisticsStart" TEXT NOT NULL DEFAULT '06:00',
ADD COLUMN IF NOT EXISTS "logisticsEnd" TEXT NOT NULL DEFAULT '18:30';

ALTER TABLE "daily_summaries"
ADD COLUMN IF NOT EXISTS "meatDistributionDone" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "logisticsDone" BOOLEAN NOT NULL DEFAULT false;
